### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by erwan** [prismicio/baked.js#23]
Not sure if it's not done or if I didn't found it, but is there a way to generate multiple pages?

Image a blog with hundreds of posts. Typically, what would seem to be the "baked" approach is:

 * Generate a first page with only 5 results
 * Include a "next page" link at the bottom
 * Generate the next page, for example with ".../p2" in the URL
... And so on, recursively until we reach a page that has no next page.

Is that possible currently or does it requires an update to baked code?

**Comment by dohzya** [comment]
It's already possible: just add “`page`” (for instance) parameter into page's `prismic-routing-param`, use it in queries and recursively call the page with the right `page` value :-)

You can watch the [vanilla example's search page](https://github.com/prismicio/baked.js/blob/master/examples/vanilla/search.html) for an example.

Note: with this example, the page number is always present in the URL (for instance the 1st page would be “`search/product/featured/1`” instead of just “`search/product/featured`”) but this could be changed by creating 2 templates (1 for the 1st page, 1 for the other ones) and customize the `prismic-routing-pattern` parameter in order to make them appears as the same page. (you can use partials to avoid code duplication)

(I let you close this issue if it's ok for you)

**Comment by erwan** [comment]
thank you!
