### ISSUE TITLE
slug example

### ISSUE THREAD

**Issue by kevinsproles** [prismicio/baked.js#25]
Trying to have the custom urls / routes use a slug rather than the id.

This post says several starter projects support it, but can't seem to get it to work in this baked.js project:
https://qa.prismic.io/2/more-control-over-my-slugs

Tried this on the parent page (index.html):

    <a href="[%= pathTo('product', {slug: product.slug}) %]">
      <h3>[%= product.getText('product.slug') %]</h3>
    </a>

And this on the detail page:

    <meta name="prismic-routing-param" content="slug">
    <meta name="prismic-routing-pattern" content="$slug">
    <script type="text/prismic-query" data-binding="product">
      [
        [:d = any(document.slug, ["$slug"])]
      ]
    </script>

**Comment by erwan** [comment]
Hi Kevin,

You shouldn't use the slug instead of the id as you can't ensure unicity, the slug is supposed to be used along with the id.

However you can add a UID fragment to your document mask and use it instead. It's pretty much like a slug you can control, and unicity within a type is guaranteed.

Here is an example project in baked.js with URLs based on UID: https://github.com/erwan/lemmonjp/

**Comment by kevinsproles** [comment]
That worked, thanks!

To answer my own question more directly, for other people to reference, here's the answer:

    <a href="[%= pathTo('product', {uid: product.uid}) %]">
      <h3>[%= product.getText('product.name') %]</h3>
    </a>

and

    <meta name="prismic-routing-param" content="uid">
    <meta name="prismic-routing-pattern" content="$uid">
    <script type="text/prismic-query" data-binding="product">
      [
        [:d = at(my.product.uid, "$uid")]
      ]
    </script>

and as @erwan said you need to go add this UID to your document mask by going into the prismic admin  settings > document masks > product > edit json
