### ISSUE TITLE
Using baked from gulp overwrites ignore options

### ISSUE THREAD

**Issue by SgtPooki** [prismicio/baked.js#26]
[This bug is regarding line 56 in gulp.js](https://github.com/prismicio/baked.js/blob/master/gulp.js#L56).

Is this really suppose to be ```_.assign(argOptions, cliOptions);``` instead of ```_.assign(cliOptions, argOptions);```? The way the code is currently written, the CLI options overwrite the argOptions passed when initializing bakedjs via the gulp/node api. I ran into this issue when I tried passing in ignore options to the config and noticed that this line was causing ignore to always be equal to an empty array.

You can test this by checking out the following snippet: 
```
_.assign(
    {
        ignore: [ 'images/*', 'js/*', 'stylus/*' ],
        srcDir: 'to_generate',
        dstDir: 'generated'
    },
    {
        ignore: []
    }
);
//results in {"ignore":[],"srcDir":"to_generate","dstDir":"generated"}
```

This file/code may be being used by other code, but ideally it shouldn't. When you're using the CLI, the cli options should overwrite the defaults, but when you're using the node api (gulp.js) you should allow users to overwrite the defaults there.

I had to fix this functionality by inserting the following code in my gulpfile.js prior to calling baked.init():
```
  process.argv.push('--ignore');
  process.argv.push('js/*');
  process.argv.push('--ignore');
  process.argv.push('images/*');
  process.argv.push('--ignore');
  process.argv.push('stylus/*');
```

I will go ahead and presume this is an error and submit a PR.

**Comment by dohzya** [comment]
There was an error, however it does not come from the order of the `assign`'s parameter but instead from the fact than `assign` replaces an array with the other instead of merging them.

I pushed a commit which fixes this behavior, please tell-me if it still does not work for you :-)

**Comment by dohzya** [comment]
Oh, I answered your 3 comments but I forgot the essential part: thank you very much for having given the alert, and even more for having proposed a PR to fix it! :grinning:

**Comment by SgtPooki** [comment]
Glad I could help. =) 

One comment though; That works for this specific issue, but are you sure you want argOptions to be the destination and cliOptions the source for the _.assign operation? The order is very important because the first will have any like properties overwritten by any subsequent properties. https://lodash.com/docs#assign.

I was trying to say that the order *is* important because you should *want* to override cliOptions with argOptions when dealing with the gulp.js tasks. That's what I would expect to happen as a user. With your fix, you're still going to overwrite all other argOptions with cliOptions. Any additional default cliOptions are going to run into this same scenario with the gulp usage of baked.js because all properties except ignore are going to be overwritten by cliOptions. 

I am probably missing some edge cases you're much more aware of being more familiar with the code base, but from an outside perspective, it really seems like it would be much more future proof and intuitive to simply have any values that are set on argOptions overwrite cliOptions when using baked.js from gulp, and have cliOptions overwrite argOptions when using the CLI.

**Comment by dohzya** [comment]
Imho, if the config file's settings don't work in a specific context, you want have a way to override them… and that's where the CLI options are really useful.

That's why I really think the right order is (from higher priority to lower priority) : 

1. CLI arguments
2. ENV variables
    - baked doesn't support them for now
3. local config file
4. global config files (`$HOME/myapp.cfg` then `/etc/myapp/config` for instance)
    - baked doesn't support them for now
5. hard-coded values

This way you can define values that should work in most cases, but you always can override then in more specific contexts.

The very important rule here is that, when a parameter is not set in a layer N, the value of the layer N+1 MUST be used (using the same rule if not found in this N+1 layer).

That's the problem we add with `ignore`: [it is (the only parameter) always defined in the `cliOptions`](https://github.com/prismicio/baked.js/blob/master/src/cli.js#L25) (even if not set by the user), so the config's value never had a chance to be used. One way to fix this would be to not set this field when it's not used, but I choose to merge it instead because I think it's more friendly this way (no need to re-specify the gulpfile's ignore values in the CLI) :-)

So I don't see this commit as a specific fix for a more generic problem but as a specific fix for a specific bug in a more generic problematic :-p

Well, that's it for my point of view :smile:

If you don't agree and/or see problems I didn't catch, I'm eager to know ;-)
Maybe you use case is different?
